name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Linting
        run: |
          cd frontend
          npm run lint

      - name: Run Tests
        run: |
          cd frontend
          npm test

      - name: Build Project
        run: |
          cd frontend
          npm run build
